USE ROLE ACCOUNTADMIN;

-- 1. Create the schemas for dbt
CREATE SCHEMA IF NOT EXISTS FINTECH_DATA.DBT_MTHIRUMALASETTI_SILVER;
CREATE SCHEMA IF NOT EXISTS FINTECH_DATA.DBT_MTHIRUMALASETTI_GOLD;

-- 2. Grant Database permissions
GRANT USAGE ON DATABASE FINTECH_DATA TO ROLE PC_DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE FINTECH_DATA TO ROLE PC_DBT_ROLE;

-- 3. Grant Schema permissions
GRANT ALL PRIVILEGES ON SCHEMA FINTECH_DATA.DBT_MTHIRUMALASETTI_SILVER TO ROLE PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA FINTECH_DATA.DBT_MTHIRUMALASETTI_GOLD TO ROLE PC_DBT_ROLE;
